### ISSUE TITLE
Investigate T1 bomber having wrong dps on unit stats

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/nomads#586]
In general this needs a bit of testing and investigation since it deals 300 damage but shows up as dealing 150 which is wrong.

**Comment by Apofenas** [comment]
The reason is none existing database is capable to represent this kind of fire circle. It is the case for Bouncer for example. I believe Rackover was working on it before she left. There are 5 projectiles x 30 damage each which is 150 total, but weapon has 2 MuzzleBones and RackFireTogether is true so the amount of projectiles is doubled which isn't calculated by DB.

Not sure what's better: to fix DataBase algorithm so it calculates crappy fir circle or to fix crappy fire circle for units. I'll do 2d for nomads, FAF things are up to Game Councilor and balance team. Previous GC did some research on it, but didn't do anything to fix the issue.

**Comment by Apofenas** [comment]
Should be fixed in #596

**Comment by Exotic-Retard** [comment]
hmm. we will close this for now but could fix it anyway :D
