### ISSUE TITLE
Sim stops when a unit is trying to fire

### ISSUE THREAD

**Issue by Garanas** [FAForever/nomads#652]
When a nomads-related unit attempts to fire a projectile the simulation just freezes and that is the end of it. The UI thread still runs. There's nothing in the logs. It is likely some infinite loop that triggers, but I wouldn't know where to start looking.

@Exotic-Retard any idea where to start the search?

**Comment by Garanas** [comment]
In this case it is just a unit that is trying to shoot, I don't imagine you attached entities to projectiles

**Comment by Exotic-Retard** [comment]
no nothing like that should happen, but im unfamiliar with the latest faf patch so whatever broke was due to some incompatibility there.

If what i wrote above doesnt ring any bells, then i guess the hard way is the way to find it xD

i.e. running nomads from source with both faf and nomads github repos (the regular nomads dev setup), then doing a binary search through the commits in the faf repo and seeing where it starts breaking.

sadly i dont have time to look into this right now :/

**Comment by speed2CZ** [comment]
@Garanas this commit seems to be responsible https://github.com/FAForever/fa/commit/36f08d50f74a336b5ebece27e6bf3610158a27f4

**Comment by Exotic-Retard** [comment]
Alright hot fixed in latest nomads release.

It was related to multiple inheritance - nomads nuke projectile has multiple inheritance on its class.

I dont know why that freezes the sim but it does. Perhaps there were some changes or interactions with how the tables are arranged? In any case this seems like an underlieing issue of some kind. And pretty serious too if it completely freezes sim.

@Garanas can you investigate? Thanks :>
